[ComfyGrid.ui.language]
type = "dropdown"
choices = ["auto", "en", "ja"]
default = "auto"

[ComfyGrid.ui.color_theme]
type = "dropdown"
choices = ["auto", "light", "dark"]
default = "auto"

[ComfyGrid.ui.show_nsfw]
type = "checkbox"
default = true

[ComfyGrid.ui.model_tree_view]
type = "checkbox"
default = true

[ComfyGrid.ui.node_color]
type = "radio"
default = "group"
choices = ["none", "node", "group", "node_priority"]

[ComfyGrid.ui.group_tabify]
type = "dropdown"
choices = ["none", "all_top_groups"]
default = "all_top_groups"

[ComfyGrid.ui.common_tab_board]
type = "checkbox"
default = true

[ComfyGrid.ui.always_show_node_focus_button]
type = "checkbox"
default = false

[ComfyGrid.ui.simple_node_mode]
type = "checkbox"
default = false

[ComfyGrid.ui.model_thumbnail_width]
type = "slider"
default = "160"
minimum = "128"
maximum = "256"
step = "8"

[ComfyGrid.ui.gallery_image_max_size]
type = "slider"
default = "448"
minimum = "256"
maximum = "768"
step = "8"

[ComfyGrid.ui.system_monitor]
type = "radio"
default = "top"
choices = ["none", "top", "left"]

[ComfyGrid.system_monitor.cpu]
type = "checkbox"
default = true

[ComfyGrid.system_monitor.ram]
type = "checkbox"
default = true

[ComfyGrid.system_monitor.gpu]
type = "checkbox"
default = true

[ComfyGrid.system_monitor.vram]
type = "checkbox"
default = true

[ComfyGrid.system_monitor.temp]
type = "checkbox"
default = true

[ComfyGrid.save.directory]
type = "text"
default = "save"

[ComfyGrid.save.create_subdirectory]
type = "checkbox"
default = true

[ComfyGrid.save.subdirectory_name_format]
type = "text"
default = "{date}"

[ComfyGrid.save.image_filename_format]
type = "text"
default = "[{ckpt_name}]_{datetime}_({seed})"

[ComfyGrid.save.image_format]
type = "dropdown"
choices = ["original", "png", "webp", "jpeg", "jxl"]
default = "original"

[ComfyGrid.save.image_quality]
type = "slider"
default = "90"
minimum = "1"
maximum = "100"
step = "1"

[ComfyGrid.save.image_embed_metadata]
type = "checkbox"
default = true

[ComfyGrid.ollama.url]
type = "text"
default = "http://localhost:11434"

[ComfyGrid.ollama.model]
type = "text"
default = "llama3.1:8b"

[ComfyGrid.ollama.system]
type = "textarea"
default = "You are an AI artist."

[ComfyGrid.ollama.translate_timing]
type = "dropdown"
choices = ["on_generate", "on_blur", "manual"]
default = "on_generate"
